PLAN-600 add count and query to people
ChicagoWorldcon/planorama pull request #479
Opened 2022-07-25 14:24 UTC by balen

2022-07-26 23:12 UTC, Gailbear requested changes
should include invisible, says the ticket. any idea why you didn't write it that way?

2022-07-26 23:12 UTC, Gailbear commented on app/models/person.rb
> +      .and(schedule[:session_assignment_name].in(['Moderator', 'Participant']))
```suggestion
      .and(schedule[:session_assignment_name].in(['Moderator', 'Participant', 'Invisible']))
```

2022-07-26 23:12 UTC, Gailbear commented on app/models/person.rb
> +              .where("person_schedules.session_assignment_name in (?)",['Moderator', 'Participant']) #, 'Invisible'
```suggestion
              .where("person_schedules.session_assignment_name in (?)",['Moderator', 'Participant', 'Invisible'])
```

2022-07-27 00:54 UTC, balen commented on app/models/person.rb
> +      .and(schedule[:session_assignment_name].in(['Moderator', 'Participant']))
done

2022-07-27 00:56 UTC, Gailbear approved these changes

2022-07-27 01:36 UTC, merged