Add surveys tab to person flyout
ChicagoWorldcon/planorama pull request #55
Opened 2021-11-13 22:28 UTC by ralphlevan

2021-11-13 22:56 UTC, Gailbear requested changes
see if it works on the col-12 div?

2021-11-13 22:56 UTC, Gailbear commented on app/javascript/app.vue
> +        </div>
```suggestion
        <div :class="['col-12 scrollable', { 'col-sm-9': loggedIn, 'col-xl-10': loggedIn}]">
          <router-view></router-view>
        </div>
```

2021-11-14 02:24 UTC, ralphlevan commented on app/javascript/app.vue
> +        </div>
Honestly, I was scared of the syntax on that div and thought it would be safer to just wrap it. I'll try `<div :class="['col-12 scrollable', ...` tomorrow

2021-11-14 02:46 UTC, ralphlevan commented on app/javascript/app.vue
> +        </div>
Ooo! Way better

2022-01-17 18:53 UTC, merged